import os
import json
import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI
from private_prompts_multi import get_extraction_prompt

load_dotenv()

# Initialize OpenAI client
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

def run_extraction_agent(chunk_text, toc_section):
    """Sends the valid text chunk to Agent 2 to extract raw text and tables."""
    system_prompt = get_extraction_prompt(toc_section)
    
    try:
        response = client.chat.completions.create(
            model="gpt-4o", # Using the heavy model for high-fidelity table extraction and semantic binding
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Extract the rules and tables from this chunk:\n\n{chunk_text}"}
            ],
            response_format={"type": "json_object"},
            temperature=0.0
        )
        return json.loads(response.choices[0].message.content)
        
    except Exception as e:
        print(f"[!] Agent 2 Error: {e}")
        # Return empty array so the pipeline doesn't crash, but you can see the failure in the log
        return {"extracted_rules": []}

def get_resume_index(log_file_path):
    """
    FAIL-SAFE CHECKPOINTING: 
    Opens the output JSONL file and physically counts the completed lines. 
    Returns the exact index where the script should resume.
    """
    if not os.path.exists(log_file_path):
        return 0
    
    try:
        with open(log_file_path, 'r', encoding='utf-8') as f:
            completed_lines = sum(1 for line in f)
        return completed_lines
    except Exception as e:
        print(f"[!] Error reading checkpoint file: {e}")
        return 0

def convert_jsonl_to_csv(jsonl_filepath, csv_filepath):
    """Flattens the secure JSONL tracker into a human-readable CSV for review."""
    print(f"\n[Post-Processing] Converting {os.path.basename(jsonl_filepath)} to CSV...")
    
    flattened_data = []
    
    if not os.path.exists(jsonl_filepath):
        print(f"[!] JSONL file not found for conversion: {jsonl_filepath}")
        return

    with open(jsonl_filepath, 'r', encoding='utf-8') as f:
        for line in f:
            if not line.strip():
                continue
                
            data = json.loads(line)
            source_index = data.get("source_index", "N/A")
            original_text = data.get("original_triage_text", "")
            
            # Navigate into the extracted payload
            extracted_payload = data.get("extracted_data", {})
            rules_array = extracted_payload.get("extracted_rules", [])
            
            # Flatten out the distinct rules
            for rule in rules_array:
                flattened_data.append({
                    "Source CSV Row": source_index,
                    "TOC Section": rule.get("toc_section"),
                    "Is Boilerplate": rule.get("is_boilerplate"),
                    "Raw Requirement Text": rule.get("raw_requirement_text"),
                    "Illustrative Table (Markdown)": rule.get("illustrative_table_markdown"),
                    "Original Text Chunk (For Comparison)": original_text
                })

    if not flattened_data:
        print("No extracted rules found to convert.")
        return

    # Convert to DataFrame and save
    df = pd.DataFrame(flattened_data)
    df.to_csv(csv_filepath, index=False, encoding='utf-8-sig')
    print(f"[Success] {len(flattened_data)} rules perfectly formatted and saved to {os.path.basename(csv_filepath)}.\n")

def run_extraction_pipeline(triage_csv_path, output_jsonl_path, output_csv_path):
    print(f"Loading Triage Log: {triage_csv_path}")
    
    # Load the CSV generated by Agent 1
    df = pd.read_csv(triage_csv_path)
    
    # Filter ONLY the chunks Agent 1 flagged as containing a rule
    valid_chunks = df[df['Contains Rule'] == True].reset_index(drop=True)
    total_valid = len(valid_chunks)
    
    print(f"Agent 1 approved {total_valid} chunks for extraction.")
    
    # --- FAIL-SAFE TRIGGER ---
    start_index = get_resume_index(output_jsonl_path)
    
    if start_index > 0:
        if start_index >= total_valid:
            print("The log file indicates all chunks have already been extracted!")
            # Still run the CSV conversion just in case they deleted the CSV but kept the JSONL
            convert_jsonl_to_csv(output_jsonl_path, output_csv_path)
            return
        print(f"Found existing extraction log. Resuming safely at chunk {start_index + 1} of {total_valid}...")
    else:
        print("Starting fresh Extraction run...")

    # Process chunks using JSON-Lines format in APPEND mode ('a')
    with open(output_jsonl_path, 'a', encoding='utf-8') as outfile:
        
        for i in range(start_index, total_valid):
            row = valid_chunks.iloc[i]
            chunk_text = row['Original Text Chunk']
            toc_section = row['TOC Section']
            
            print(f"Agent 2 extracting chunk {i+1} of {total_valid}... (TOC: {toc_section})")
            
            # Run the extraction (API Call)
            extraction_data = run_extraction_agent(chunk_text, toc_section)
            
            # Create a secure payload for Agent 3
            log_entry = {
                "source_index": int(row.name), # Track original index from the filtered CSV
                "original_triage_text": chunk_text,
                "extracted_data": extraction_data
            }
            
            # IMMEDIATE SAVE: Write line-by-line (JSONL format). 
            outfile.write(json.dumps(log_entry) + "\n")
            outfile.flush()

    print("\nAPI Extraction phase complete! Initializing post-processing...")
    
    # --- AUTOMATIC CSV GENERATION ---
    convert_jsonl_to_csv(output_jsonl_path, output_csv_path)

if __name__ == "__main__":
    # Bulletproof file paths
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
    TRIAGE_CSV = os.path.join(SCRIPT_DIR, "triage_log.csv")
    EXTRACTION_LOG = os.path.join(SCRIPT_DIR, "extraction_log.jsonl")
    EXTRACTION_CSV = os.path.join(SCRIPT_DIR, "extraction_review.csv")
    
    run_extraction_pipeline(TRIAGE_CSV, EXTRACTION_LOG, EXTRACTION_CSV)